require("jannik.plugins-setup")
require("jannik.core.options")
require("jannik.core.colorscheme")
require("jannik.core.keymaps")
require("jannik.core.commands")
require("jannik.core.autocommands")

-- Plugin configurations
require("jannik.plugins.asynctasks")
require("jannik.plugins.autopairs")
require("jannik.plugins.barbar")
require("jannik.plugins.betterwhitespace")
require("jannik.plugins.claude-code")
require("jannik.plugins.codeium")
require("jannik.plugins.comment")
require("jannik.plugins.dadbod")
require("jannik.plugins.flutter-tools")
require("jannik.plugins.go")
require("jannik.plugins.vim-grammarous")
require("jannik.plugins.lualine")
require("jannik.plugins.nvim-cmp")
require("jannik.plugins.nvim-transparent")
require("jannik.plugins.nvim-tree")
require("jannik.plugins.telescope")
require("jannik.plugins.treesitter")
require("jannik.plugins.typescript-tools")
require("jannik.plugins.undotree")
require("jannik.plugins.vimtex")
require("jannik.plugins.winresizer")

--  lsp
require("jannik.plugins.lsp.lspsaga")
require("jannik.plugins.lsp.lsp-config")
require("jannik.plugins.lsp.mason")
require("jannik.plugins.lsp.null-ls")

